### PR TITLE
Add option failOnNoGitDirectory

### PR DESCRIPTION
**Pull request by nathansgreen**
Make repository existence optional, as requested in issue #27.

### CODE REVIEW

**Comment by edeandrea** [comment]
Seems I posted the same issue with #35 

What about simply adding the [@SkipWhenEmpty](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SkipWhenEmpty.html) annotation on top of the `@InputFiles` annotation on `GenerateGitPropertiesTask.getSource()` method inside `GitPropertiesPlugin`?

**Comment by nathansgreen** [comment]
I don't see how it can be optional if it's specified with an annotation like that.

**Comment by edeandrea** [comment]
The behavior would be a little bit different. Today if there is no git repo the `generateGitProperties` task will fail. Adding the annotation would simply skip the task if the git repo wasn't there. I guess what you are proposing is functionality which would allow the user to decide the behavior in either case, rather than leaving the plugin itself to make the decision.

**Comment by nathansgreen** [comment]
I like the existing default behavior, which is to fail the build. It cuts down on surprises and prevents programmer mistakes, saving lots of time troubleshooting. Silently skipping a task that our production systems rely on is dangerous, so I prefer it to be done explicitly.

**Comment by nathansgreen** [comment]
The current diff is now a lot simpler. Let me know what you think.

**Pull request merged**
