### PR TITLE
Add git.remote.url property

### PR DESCRIPTION
**Pull request by sleclercq**
I wanted to visualize the git remote url to help with scripts which create a changelog from one sha to another on multiple microservices.

My groovy is quite weak so I think this pull request needs some improvements, at least to avoid corner cases where a git remote isn't available

### CODE REVIEW

**Comment by n0mer** [comment]
@sleclercq can you please explain your use case? 

Speaking of myself - i enrich MANIFEST.MF with git metadata, and create dedicated URL that exposes this manifest in JSON format. This approach might be good enough for your use case, isn't it?

**Comment by sleclercq** [comment]
Hi @n0mer ,

My use case is generating a list of commits between two arbitrary deliverables. I would like to be sure that the deliverables are from the same repo/fork. Having the metadata exposed with an endpoint is interesting to know the version of the currently deployed deliverable, but doesn't give information about the gap between the least deployment and the newest one.

I agree with you that there are several ways to skin that cat (creating tags or releases automatically, adding data outside the deliverable, ...) and I just wanted to share this approach if it had any interest to you (as maven-git-commit-id-plugin does it).

**Comment by Endron** [comment]
Hi,

I do not see the idea of putting the remote URL in the git.properties that useful. There are in fact a few problems:

1. This is an internal information containing at least an hostname and maybe details like IP address or SSH username. I do not think you want to put this in an public endpoint. 
2. The URL used by the build server to clone the repository might not be resolvable anywhere else. In an enterprise environment it is likely not routed from the internet.
3. Commit IDs should be enough to compare anyways. This comes down to: Why is the remote that build the release important? Do you not have a central repository where all commits are stored? If you do you can always compare based on diffs between the commit IDs.

Just my humble opinion on this.

Best Regards,
Tobias

**Comment by sleclercq** [comment]
Hi Tobias,

All are valid points. Points 1 & 2 can be solved with a plugin property.

I have trouble understanding point 3 given what I think a common CI use case is :
- clone/checkout from a remote repo
- build the application and store the commit ids in the deliverable
- deploy the application somewhere

This implies that any tool/dashboard which would be used to compare 2 deliverables should be configured with the same remote repo. This gets more complex/error prone when you have several central repositories (github, internal gitlab, contractor's gitlab, ...).

Again I understand it is not a must have for this project, and I have several other ideas to work around this issue so if it's not wanted it's fine to close it.

Cheers,
Stephane.

**Comment by tha2015** [comment]
I don't the reason for NOT supporting this feature. Generally I would prefer a powerful plugin to support as many properties as possible (even "custom" properties) and I should be responsible for what I asked for, rather than a tool which tries to be "smart" and blocks me from many things.

**Comment by edeandrea** [comment]
Just to add my 2 cents - it would be nice if the remote origin url was available in the git.properties (or at least a way for consumers to customize what they want). My use case is that in our enterprise we would like the information exposed via the spring-boot /info actuator. Like @Endron mentioned we would not want to expose this outside of our enterprise, which is why all of our actuator endpoints are blocked from outside my company's network. We're already putting the full info as well as the build info into the /info actuator endpoint - it would be nice to also have the Git remote origin url there as well.

**Comment by n0mer** [comment]
@sleclercq can you look at merge conflicts?

**Comment by Endron** [comment]
@n0mer I would advocate just closing this pull request as it is one and a half years by now.

At the very least I would advise adding some test cases for the "stripCredentialsFromOriginUrl" function.
Just by reading it I do not think it is handling usernames and passwords in URLs as well as SSH Strings in a meaningful way. It might even leak passwords into the generated properties.

Examples that need testing in my eyes include:

- user@server:repo.git
- ssh://user@server/repo.git
- https://user:password@git.server/repo.git
- https://user@git.server/repo.git
- https://git.server/repo.git

**Comment by sleclercq** [comment]
Hi, yes I am sorry I don't have time to work on this anymore. I also believe that if the MR wasn't accepted 1.5y ago the situation has not changed so it is fine with me to close it.

**Comment by n0mer** [comment]
@sleclercq @Endron this functionality can be implemented by custom properties from https://github.com/n0mer/gradle-git-properties/pull/56

**Pull request closed without merging**
